### ISSUE TITLE
[EPIC] Rework Traceloop

### ISSUE THREAD

**Issue by marga-kinvolk** [kinvolk/inspektor-gadget#371]
Traceloop is not like our other gadgets, it’s “old” (for eBPF purposes), it doesn’t integrate with Gadget Tracer Manager but rather runs as a separate binary. We would like to integrate it better and update it to current practices.

This epic includes: 

- [ ] #338 
- [ ] Migrate to CO-RE and newer practices. 
- [ ] Integrate with Gadget Tracer Manager 
- [ ] Expose traceloop as a golang package used by Inspektor Gadget, that other tools can also use. 

[All gadget/traceloop issues](https://github.com/kinvolk/inspektor-gadget/labels/gadget%2Ftraceloop)

**Comment by marga-kinvolk** [comment]
One thing to consider when reworking traceloop: instead of it being a separate gadget, it could make sense for it to be a functionality available for any of our tracing gadgets. Something like `kubectl-gadget trace exec --loop`. We would need to add a tracer that traces ALL syscalls, like traceloop does, because we currently don't have that one.
