### ISSUE TITLE
[EPIC] Improve local-gadget filtering 

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#644]
## Current situation

Currently, it is only possible to filter gadgets by container name. So, we would like to provide the possibility to filter by all these parameters: 
- Container Name: 
  - Already supported. 
- Container ID:  
  - There could be multiple containers with the same name. 
  - Some containers do not have a name (e.g., pause containers on Containerd) so the container ID is also needed. 
- Container Runtime (Currently: Docker, Containerd or CRI-O) 
- Kubernetes metadata: 
  - Users that are debugging containers created through Kubernetes, could need to trace all the containers belonging to the same Kubernetes pod or namespace. This information is provided by the container runtime in the labels, so we don’t need the Kubernetes API Server to be up. For instance: 
    - `"io.kubernetes.pod.name": "coredns-78fcd69978-zp5gx"`
    - `"io.kubernetes.pod.namespace": "kube-system"`
- Container Runtime namespace: 
  - Some container runtimes, like Containerd, support the concept of "namespace". Users that have containers created by Kubernetes and others created directly with ctr (containerd CLI) could need to trace only the containers created by Kubernetes, this could be achieved by filtering the `k8s` namespace of Containerd. 

This epic is composed of the tasks to support this kind of filtering: 

1. Currently, we already support this for Docker, so we need to do the same for Containerd and CRIO. 
    - [ ] TODO: Create an issue to add support to non-Kubernetes containers with Containerd and CRI-O. 

2. Improve enrichment of containers done by WithMultipleContainerRuntimesEnrichment:
    - [ ] TODO: Create an issue for enrichment. This enricher needs to be improved to add the following information: Container Runtime Name, Kubernetes Metadata: Pod and namespace, Container runtime Namespace. 
    - [ ] TODO: Create an issue to create an internal data structure to store the Container definition and do not use the one from gRPC. Wait after @alban finishes the PR where he is adding more fields to it. 
  
3. Integration tests:
    - [ ] TODO: Create an issue to add integration test for local-gadget

**Comment by mqasimsarfraz** [comment]
Closing, since all the sub-issues have been merged!
