### ISSUE TITLE
ci/integration-tests: Deadlock during the clean-up of the SPO

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#724]
## Description

[In this case](https://github.com/kinvolk/inspektor-gadget/runs/7121449560?check_suite_focus=true) I found that there was a deadlock situation that seems to happen when the pod using a given seccomp profile is deleted and for some reason (maybe it was being deleted as well) the Security Profiles Operator (SPO) does not remove the finalizer `in-used-by-pod-xyz` from its seccomp profile. It causes that such seccomp profile is never deleted and the clean-up procedure of the integration tests remains blocked waiting for its deletion.

## Impact

The workflow run could stay running forever.

## Additional information

I don't see a clean solution for this because I haven't found a way to synchronize the undeployment of the SPO with the running tests. [Testing.M](https://github.com/kinvolk/inspektor-gadget/blob/83ff89e493ae4702ce1346cb5018eb8b39365607/integration/integration_test.go#L264) does not have any method to stop the running tests so there will always be the possibility that we start undeploying the SPO and at the same time one of the tests deletes a pod that is using a seccomp profile. The only workaround I that the clean-up procedure of the SPO forces the deletion of all the seccomp profiles by manually removing the finalizers. It seems quite brutal but, in the end, we already know that the pod using it will be also deleted soon (or in the deadlock case, was already deleted). In fact, this is what I am doing manually when it happens.

## TODO: 

- [ ] Investigate how the undeployment is managed in the SPO's integration-tests.
- [ ] If we have a different use-case from the SPO integration-tests, check if it is easy to implement the workaround that forces the deletion of all the seccomp profiles by removing the finalizers (BTW, like already done with our Trace CRD, see [here](https://github.com/kinvolk/inspektor-gadget/blob/ba7ed93fde02134219d9bb7a5ad01554be6fe114/cmd/kubectl-gadget/undeploy.go#L119-L131)).
- [ ] If the workaround does not work or is complicated to be implemented, consider to disable in ARO the tests that use the SPO or deploying the SPO once and never removing it.
